### PR TITLE
Add support for Gitlab & Bitbucket

### PR DESCRIPTION
**Pull request by fspoettel**
Hey @vencax, thank you so much for getting the ball rolling with this provider and doing all the hard reverse-engineering work. This PR implements Gitlab and Bitbucket support and also refactors critical parts of the codebase to be more modular.

_Note on the code-size_: Most of it is the `package-lock.json` that npm recommends to commit for CI.

## Changes in this PR

* Adds an `oAuthClient`-class that interfaces with the `simple-oauth`-module.
* Add `oAuthFactory` that applies default `oAuth`-settings for Gitlab and Bitbucket according to a `PROVIDER` env-variable. This change is backwards-compatible and will not break existing implementations as it defaults to `github`
* Add handlebar views, move logic from rendering layer to `oAuthClient`-class
* Add index-view that behaves like netlify-cms/Auth for debugging purposes
* Add CRSF-protection by validating valid `state`-returns from the oAuth endpoints
* Add eslint with `standard`-config

## To-Do

 - [ ] Add specs for critical functionality
 - [ ] Update documentation

### CODE REVIEW

**Comment by vencax** [comment]
Hi, Felix. Thank you for your attention and effort. Let me get this straight: is there any extras necessary to authorize through gitlab or bitbucket than through github? If not, your PR is refactoring the original code (since the other provider setting is settable via envvars), is it?

**Comment by fspoettel** [comment]
@vencax No extras necessary apart from some configuration differences (e.g. bitbucket does not need scopes set and throws if scopes are different). Apart from that, yes it's refactoring and some minor fixes in regards to error handling and security.

**Comment by fspoettel** [comment]
Also, feel free to close if you don't like the changes or feel that they are not necessary. I did the refactoring mostly for myself but thought that at least opening a PR would do no harm 🙂

**Comment by vencax** [comment]
Nice. I am fan of simple code without syntactic sugar. I will wait if some other comments in the PR appear and will see what to do then. 
But if you have done some research on the other providers, you could update README.md and send another PR. It would be great!
Cheers :)

**Comment by fspoettel** [comment]
@vencax https://github.com/vencax/netlify-cms-github-oauth-provider/pull/8/files#diff-a7748843fbda5167d065231e3a2e7a1f has all the information needed

**Comment by fspoettel** [comment]
I will open a PR with the documentation changes in the next days, closing this PR :)

**Pull request closed without merging**
