### PR TITLE
Github Enterprise support added, documentation updates.

### PR DESCRIPTION
**Pull request by tortilaman**
- Added new GIT_HOSTNAME environment variable to allow configuration of Github Enterprise endpoint.
- Readme additions for each config option and creating an Oauth app on Github

### CODE REVIEW

**Review by vencax — COMMENTED** [review]
Hi, please, don't use semicolons, follow https://standardjs.com/rules.html

**Comment by tortilaman** [comment]
Thanks for the link vencax. Will make updates.

**Comment by vencax** [comment]
Hi, this pull became too messy for me, so I have collected all the changes and made this commit: https://github.com/vencax/netlify-cms-github-oauth-provider/commit/62b84c043ab152c0c0ead16604abb1ac3adb25d9

Closing this PR. If you feel I have forgotten something, comment here.
Anyway: thanks to you all who was involved :)

**Comment by tortilaman** [comment]
That's fine. Sorry for all the noise.

**Pull request closed without merging**
