### PR TITLE
adds gitlab provider

### PR DESCRIPTION
**Pull request by davidayalas**

### CODE REVIEW

**Comment by vencax** [comment]
Hi, I am not sure if the login window has to be in blank target. What do you think? How about to have it customizable?

**Comment by davidayalas** [comment]
I forgot to cleanup it, it was for testing purposes only

**Comment by vencax** [comment]
Ok, can you promise, that these changes wont brake it all? :) I don't have time to test it now :/

**Comment by davidayalas** [comment]
Hey! Yes... I have two test sites, one with github and one with gitlab and they are working fine ;)

**Pull request merged**
