### PR TITLE
feat: added github action

### PR DESCRIPTION
**Pull request by ramank775**
Added github action to publish docker images

### CODE REVIEW

**Comment by ramank775** [comment]
@vencax you need to add following variables/secret in repository environment (CI)
```
REGISTRY_IMAGE= 
DOCKERHUB_USERNAME=
DOCKERHUB_TOKEN=
```

**Comment by vencax** [comment]
I have created this: https://hub.docker.com/r/vencax/netlify-cms-github-oauth-provider
What goes into REGISTRY_IMAGE var in this case?

**Comment by ramank775** [comment]
Registry image will be the repository name for docker hub in your case 
REGISTRY_IMAGE=vencax/netlify-cms-github-oauth-provider

**Comment by vencax** [comment]
DOne successfuly. Thanks 4 support

**Pull request merged**
